Platform
Broscorp-net/traineeship pull request #1052
Opened 2022-03-10 13:26 UTC by Shurick2211

Platform

2022-03-15 20:15 UTC, pesua reviewed
Мне пишет
Warning: nonterminated comment in line 8 Error: :9: syntax error near line 9

У тебя диаграмма нормально строится?

2022-03-15 20:17 UTC, pesua requested changes

2022-03-15 20:17 UTC, pesua commented on module1/src/main/java/net/broscorp/patform/Platform.gv
> +  необходимое для компиляции байт-кода в машинный код.*/
Это странное утверждение, проверь его, пожалуйста

2022-04-10 18:57 UTC, ArtemKonovalov commented on module1/src/main/java/net/broscorp/patform/Platform.gv
> +  "Java Virtual Machine (JVM)" -> "Java Development Kit (JDK)"
Судя по диаграмме, JDK не содержит JRE. Перепроверь

2022-04-11 06:23 UTC, Shurick2211 commented on module1/src/main/java/net/broscorp/patform/Platform.gv
> +  "Java Virtual Machine (JVM)" -> "Java Development Kit (JDK)"
Конечно же содержит, просто хотелось подчеркнуть, что есть два конечных продукта JRE (виртуальная машина + утилиты), и JDK (в котором конечно же содержится JRE + инструменты разработки, что указано в комментарии).

2022-04-11 18:07 UTC, ArtemKonovalov commented on module1/src/main/java/net/broscorp/patform/Platform.gv
> +  "Java Virtual Machine (JVM)" -> "Java Development Kit (JDK)"
Окей, но в задании требуется `2. Показать в каком порядке они включают друг друга, с чем работают.`, а не конечные продукты.
Если хочешь показать варианты ветвления, то, например, можно показать что входит в JDK помимо JRE.

2022-04-12 17:59 UTC, Shurick2211 commented on module1/src/main/java/net/broscorp/patform/Platform.gv
> +  "Java Virtual Machine (JVM)" -> "Java Development Kit (JDK)"
Ну, ОК.

2022-04-17 18:10 UTC, akellanotavailable commented
Круто, теперь другое дело!

2022-04-17 18:10 UTC, closed without merging