Patform
Broscorp-net/traineeship pull request #1062
Opened 2022-03-10 18:00 UTC by Nikola-jpg

2022-03-15 20:13 UTC, pesua requested changes
В пуле должны быть только изменения относящиеся к этому заданию. Исправь остальные, пожалуйста, если там такая же история.

2022-03-15 20:13 UTC, pesua commented on module1/src/main/java/net/broscorp/patform/graph.gv
> +digraph graphName {
Warning: nonterminated comment in line 12 Error: :13: syntax error near line 13

2022-03-16 07:46 UTC, Nikola-jpg commented on module1/src/main/java/net/broscorp/patform/graph.gv
> +digraph graphName {
Нужно убрать комментарии? Не пойму где проблема

2022-04-17 19:14 UTC, akellanotavailable commented
красивое

2022-04-17 19:14 UTC, closed without merging