equals.hashcode
Broscorp-net/traineeship pull request #1098
Opened 2022-03-11 19:17 UTC by antono0106

2022-03-19 17:57 UTC, pesua requested changes

2022-03-19 17:57 UTC, pesua commented on module1/src/main/java/net/broscorp/equals/hashcode/EqualsHashCode.java
> +    hash = 31 * hash + getInteger().hashCode();
Привет NPE =)

2022-03-19 17:57 UTC, pesua commented on module1/src/main/java/net/broscorp/equals/hashcode/EqualsHashCode.java
> +    hash = 31 * hash + getInteger().hashCode();
Зачем использовать геттеры на приватных полях?

2022-03-19 17:57 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashCodeTest.java
> +    for (int i = 0; i < 5; i++) {
Лучше отдельные инварианты тестировать в разных методах, когда тест упадёт - сразу будет ясно какое правило сломалось.

2022-03-19 17:57 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashCodeTest.java
> +      new Random().nextBytes(bytes1);
Прикольная идея

2022-04-28 02:59 UTC, akellanotavailable commented
Ого, оч круто сделал!

2022-04-28 02:59 UTC, closed without merging