strings
Broscorp-net/traineeship pull request #1143
Opened 2022-03-14 09:35 UTC by Kiriche

2022-04-03 09:47 UTC, boryakam requested changes
Предлагаю изучить StringBuilder и внедрить где уместно работу с ним.

2022-04-04 09:05 UTC, Kiriche commented
Когда я делал этот пулл реквест я был горд тем, как быстро и ловко я всё сделал.

Щас открываю вносить правки и вижу среди прочих косяков вот это:
if (s.equals(reversed)) {
      return true;
    } else {
      return false;
    }

Огонь.

2022-04-04 10:58 UTC, boryakam approved these changes

2022-04-04 10:58 UTC, boryakam commented
Good job!

2022-04-04 10:58 UTC, closed without merging