primitives
Broscorp-net/traineeship pull request #1160
Opened 2022-03-15 11:35 UTC by pro100volodya

2022-03-15 12:08 UTC, pro100volodya reviewed
primitives2

2022-03-16 09:14 UTC, pesua requested changes
Не вижу илюстрации погрешности при операциях с числами с плавающей точкой.

2022-03-16 09:14 UTC, pesua commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTests.java
> +    Assertions.assertEquals(valueForCorrectConversion, (int) valueForCorrectConversion);
Просили показать какие могут быть проблемы. Тут все хорошо.

2022-03-16 09:14 UTC, pesua commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTests.java
> +    Assertions.assertEquals(valueForCorrectConversionWithAdmissibleError,
Этот тест пройдёт даже если никакой погрешности нет. Задача была продемонстрировать погрешность при конвертации.

2022-03-16 15:53 UTC, pro100volodya reviewed
remarks have been corrected

2022-07-23 13:08 UTC, closed without merging