boxing
Broscorp-net/traineeship pull request #1163
Opened 2022-03-15 16:43 UTC by pro100volodya

2022-03-16 18:23 UTC, pesua requested changes

2022-03-16 18:23 UTC, pesua commented on module1/src/test/java/net/broscorp/boxing/BoxingTest.java
> +    Assertions.assertTrue(value1 == value2);
Тут будет тру не для любого числа, попробуй 300

2022-03-16 18:23 UTC, pesua commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTests.java
> +public class PrimitivesTests {
В пуле должны быть изменения тоько одного задания

2022-03-17 11:22 UTC, pro100volodya commented on module1/src/test/java/net/broscorp/boxing/BoxingTest.java
> +    Assertions.assertTrue(value1 == value2);
Да, так как в Integer данные от -128 до 127 находятся в кеше, и при инициализации в таком диапазоне объект не создается.

2022-07-23 13:08 UTC, closed without merging