gamelife
Broscorp-net/traineeship pull request #1171
Opened 2022-03-16 11:20 UTC by Kiriche

2022-03-23 18:44 UTC, pesua requested changes
Молодец что сразу сделал безконечное поле половчее.
Почини обработку исключений, пожалуйта.
Будет здорово если придумаешь как аккуратнее соседей обойти, в таком коде легко перепутать местами плюсы и минусы и посадить незаметную багу.

2022-03-23 18:45 UTC, pesua commented
Забыл сказать - аутпут файлов в комите быть не должно

2022-03-24 10:57 UTC, Kiriche commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    //cellCounter += checkState(y, x) ? 1 : 0;
Артефакт оставшийся от интеграционных тестов. Мне хватило ума изначально вставить туда эту строку, так что минут 10 я точно потратил на ловлю абсолютно лишнего бага.

2022-03-24 10:58 UTC, Kiriche commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    y = (y + ysize) % ysize;
Ага. Вот это и синхронность runLifeCycle() были самыми сложными частями задачи. Изначально тут был жуткий вложенный ифчик, который мне было слишком стыдно отправлять, поэтому решил сделать как с разделением числа на составляющие.

2022-03-24 11:17 UTC, Kiriche commented
Внес требуемые правки. Честно говоря, я не очень уверен, что сделал проверку соседей лучше и читабельнее. Я читал, что вложенные циклы это плохая практика. Еще подумаю, возможно я не вижу более красивого решения.

Исключения теперь бросают RuntimeException и крашат приложение, но логируются как IOException.

2022-03-29 19:36 UTC, pesua requested changes
Двойная вложенность в цикле это норм. Если есть тройная то стоит напрягаться.

2022-03-29 19:36 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +        cellCounter += checkState(y + row, x + column) ? 1 : 0;
Получается что сама с собой клетка тоже сравнивается?

2022-03-29 19:36 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +      throw new RuntimeException("Failed to open a file.");
Тоже не лучший способ. RuntimeException будет перехвачен где-то наверху и там потеряется пловина стека, лучше вкладывать старое исключение внутрь рантайма.
+лучше логировать когда обрабатываешь исключение а не перебрасываешь, наверху его тоже залогируют и получится две записи в логе вместо одной

2022-03-29 19:36 UTC, pesua commented on module1/src/test/resources/outputGlider.txt
> +X O O O O O O O O O O O O O O O O O O O
Просил же убрать аутпуты

2022-03-30 07:32 UTC, Kiriche commented on module1/src/test/resources/outputGlider.txt
> +X O O O O O O O O O O O O O O O O O O O
Так это же из первого коммита самого, разве нет? В актуальных изменено только 2 файла: тесты и сам gameoflife

2022-03-30 17:33 UTC, pesua commented on module1/src/test/resources/outputGlider.txt
> +X O O O O O O O O O O O O O O O O O O O
Мне не важно сколько комитов в пуле, важно какие изменения ты хочешь мерджить. 
Я сейчас не придираюсь, этот навык нужен на работе с настоящим проектом. Иначе в фалах будет бардак.

2022-03-30 17:36 UTC, pesua commented
Хорошо что убрал файлы и остальное сделал. Но билд упал 🙈
Пул с упавшим билдом тебе даже CI смерджить не даст.

2022-03-31 16:59 UTC, Kiriche commented
Подумал, что нужен комментарий.

Билд  упал

2022-04-01 07:42 UTC, closed without merging