Gcimpl
Broscorp-net/traineeship pull request #1206
Opened 2022-03-22 19:20 UTC by Shurick2211

Gcimpl

2022-03-22 19:36 UTC, Shurick2211 commented
Напишу очень коротко: в стеке хранятся ссылки на "живые" объекты (еще там могут хранится примитивы), в куче хранятся объекты все: и живые, и мусор. Мы по ссылки из стека получаем живые объекты, потом их потомков - это все мы не трогаем, соответственно все остальное в утиль :-)

2022-03-25 07:18 UTC, pesua requested changes
Стяни последние изменения себе в форк, коммит "gcimpl additional test cases" покажет почему этот алгоритм не рабочий

2022-03-25 07:18 UTC, pesua commented on module1/src/main/java/net/broscorp/gcimpl/GarbageCollectorImplementation.java
> +      aliveBeans.addAll(frames.pop().getParameters());
Было бы хорошо не опустошать существующий стек, наверное он еще кому-то нужен)

2022-03-25 12:24 UTC, Shurick2211 commented
Написал коменты в коде, и теперь дошли диаграмки  в описаловке задания (как в старом анекдоте про препода: - так объяснял, что аж сам понял...)

2022-03-29 08:40 UTC, pesua requested changes

2022-03-29 08:40 UTC, pesua commented on module1/src/main/java/net/broscorp/gcimpl/GarbageCollectorImplementation.java
> +    aliveBeans.forEach(a -> aliveBeansWithCildren.addAll(a.getFieldValues().values()));
А что с бинами, у которых вложенность больше трёх уровней?

2022-03-29 08:40 UTC, pesua commented on module1/src/test/java/net/broscorp/gcimpl/GarbageCollectorImplementationTest.java
> +    ApplicationBean service = new ApplicationBean();
Руками применять изменения - не по пацански, разберись как синхронизировать комиты, пожалуйста.

2022-03-30 15:28 UTC, closed without merging