gamelife
Broscorp-net/traineeship pull request #1226
Opened 2022-03-26 13:28 UTC by antono0106

2022-03-29 19:42 UTC, pesua requested changes
Было не легко отлаживать этот код, правда? Поддерживать будет еще сложнее.
Его не должно быть так много, если убрать всю дубликацию то решение станет гораздо понятней и короче.
Подумай как выделить повторяющиеся кусочки в методы итд.

2022-03-29 19:42 UTC, pesua commented on module1/src/test/resources/outputGlider.txt
> +O O O O O O O O O O O O O O O O O O O O
Убери это, пожалуйста. Генерируемые файлы не должны лежать в репозитории.

2022-03-29 19:42 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +            /*if (i == 0 && j == 0) {
Закоментированный код не должен попадать в репу

2022-04-28 13:13 UTC, akellanotavailable commented
хорош

2022-04-28 13:13 UTC, closed without merging