checkstyle
Broscorp-net/traineeship pull request #306
Opened 2020-08-23 07:23 UTC by nacenik

2020-08-28 12:20 UTC, nacenik commented
pom.xml брал из репозитории на гите, поэтому в последнем коммите будет показывать изменения. [тут pom.xml  до копирования с репозитория](https://github.com/Broscorp-net/traineeship/pull/306/commits/8618fce5aceeef0e65a798672e2cf88034de7a12)

2020-09-01 09:03 UTC, ZdorenkoS requested changes
Изменения в pom не принимаются...
StyledClass - ok.

2020-09-01 09:12 UTC, nacenik commented
> Изменения в pom не принимаются...
> StyledClass - ok.



> Изменения в pom не принимаются...
> StyledClass - ok.

pom был взять из проекта

2020-09-01 09:30 UTC, ZdorenkoS commented
> 
> pom был взять из проекта

Сорри, не заметил. Тогда все ок...

2020-09-06 06:13 UTC, closed without merging