Primitives
Broscorp-net/traineeship pull request #403
Opened 2020-08-28 16:08 UTC by NikitaBatalskiy

2020-09-06 06:30 UTC, Provsky commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +//package net.broscorp.generics;
Комментарии в пулах недопустимы, нужно убрать.

2020-09-06 06:33 UTC, Provsky commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    int maxIntValue = Integer.MAX_VALUE;
Это, не все примитивные типы.добавь пару тестов с другими.

2020-09-11 17:20 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    int maxIntValue = Integer.MAX_VALUE;
Тест такого же типа, но с другими примитивами?

2020-09-17 12:15 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    int maxIntValue = Integer.MAX_VALUE;
да, с примитивами других типов

2020-09-29 07:01 UTC, Pakirava-Datsuma requested changes

2020-09-29 07:01 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -}
В пулл-реквесте не должно быть видно изменений в файле, где не меняется ничего из заявленного в топике.

2020-09-29 07:01 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +  public void longToIntConvertation() {
тут и далее: conver**S**ion

2020-09-29 07:33 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -}
Изначально было сказано, что этот класс можно удалять после первого задания

2020-09-29 07:34 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> -
не знаю как отменить конкретно эти изменения

2020-09-29 14:28 UTC, Pakirava-Datsuma commented
юхуу!!!!
![image](https://user-images.githubusercontent.com/1230991/94571922-1fa2e680-0279-11eb-8d32-333ac0d4f003.png)

2020-09-29 14:28 UTC, closed without merging