valueref
Broscorp-net/traineeship pull request #405
Opened 2020-08-28 16:29 UTC by NikitaBatalskiy

2020-09-07 07:59 UTC, Provsky commented on module1/src/test/java/net/broscorp/boxing/BoxingTest.java
> +public class BoxingTest {
В отдельную ветку

2020-09-07 07:59 UTC, Provsky commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +public class PrimitivesTest {
В отдельную ветку

2020-09-07 08:03 UTC, Provsky commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // локальные
Что означет, изменения локальные?

2020-09-07 08:03 UTC, Provsky commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +//import java.util.function.Function;
комментарии убрать

2020-09-15 17:56 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // локальные
Переменная изменилась в пределах метода

2020-09-29 07:52 UTC, Pakirava-Datsuma requested changes

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // локальные
какая переменная?

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -}
could we keep this file unchanged?

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> -
could we keep this file unchanged?

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // Повторение причины выше, а значит и размер списка на 1 больше начального
Один из принципов юнит-тестирования: тесты должны быть максимально независимы. Т.е. удаление/добавление одного теста не должно крашить остальные. Это выполняется :+1: 
И, воспринимая тесты независимо, их проще читать без скроллинга. А еще лучше строка-за-строкой. Поэтому именно в тестах не зазорно, а чаще даже полезно дублировать данные, комментарии и пр. Даже в соседних строках.

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // Повторение причины выше, а значит и размер списка на 1 больше начального
конкретно этот комментарий зависит от предыдущего комментария. Если кто-то в будущем удаляет предыдущий тест с его комментарием, текущий комментарий становится бесполезным (непонятным).

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    foo.foo(number, list);
Здесь мне приходится бегать глазами от кода к объявлению переменных. Во-первых, потому что я сразу начинаю читать текст теста, пропуская переменные класса, `@Before`-метод и прочее.
Мне было бы удобно видеть здесь на переменную list, а сразу содержимое; не переменную number, а сразу число. Понимаю, что на этот список нужно сослаться в assert'е, но все-таки поднять глаза на 1 строку или в начало класса — ощутимая разница.
Во-вторых, потому что переменные названы абстрактно.
Конечно, виной тому абстрактность тестируемого класса. Но это же позволяет тебе написать тест на класс — **круче,** чем сам класс :)

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  public void listSizeShouldBe5() {
Тест проверяет **поведение** класса. "Размер списка должен быть 5" — это не поведение, а результат, говорящий о корректном поведении. Давай переименуем так, чтобы имя класса сообщало, какой поведение проверяется. Размер списка ведь не всегда должен быть 5.

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertTrue(list.size() == 5);
![image](https://user-images.githubusercontent.com/1230991/94527438-a5a23b80-023f-11eb-94ef-746595cce518.png)

2020-09-29 07:52 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertTrue(list.contains("d"));
Как насчет максимально интегрировать комментарий в код? У методов `org.junit.jupiter.api.Assertions.*` есть формы с дополнительным аргументом для текста.

2020-09-29 07:55 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // Повторение причины выше, а значит и размер списка на 1 больше начального
понял, учту

2020-09-29 07:57 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    foo.foo(number, list);
Хорошо, это тоже учту, просто думал, что раз уж переменные используются для нескольких тестов, то правильнее будет задать в @Before

2020-09-29 07:58 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  public void listSizeShouldBe5() {
понял-принял

2020-09-29 08:23 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    foo.foo(number, list);
я бы тут привел такую грань:
- если данные для тестов могут быть разными, и они связаны с тестируемым поведением — тогда пусть они будут в каждом тесте, даже если ОДИНАКОВЫ.
- если данные не связаны с тестируемым поведением и не могут измениться (иначе тесты не запустятся) — тогда это довод в пользу `@Before`

2020-09-29 10:34 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // локальные
Которая была передана в качестве параметра в метод foo()

2020-10-12 08:15 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  // локальные
так мы передали переменную или значение?

2020-10-12 08:28 UTC, Pakirava-Datsuma approved these changes

2020-10-12 08:28 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertTrue(list.contains("d"));
Ладно, это было скрытое задание со звездочкой — можно пропустить) Правильный ответ: 
`assertTrue("Список - объект, изменения в методе касаются списка везде, так как объекты передаются по ссылке, а значит список пополнился строчкой \"d\"", list.contains("d"));`

2020-10-12 08:28 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertTrue(list.contains("d"));
Пожалуйста, зарезолвь этот диалог, когда прочтешь

2020-10-12 08:28 UTC, Pakirava-Datsuma commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertTrue(list.contains("d"));
Зарезолвь этот диалог, когда прочтешь

2021-03-24 15:02 UTC, closed without merging