equals.hashcode
Broscorp-net/traineeship pull request #428
Opened 2020-08-30 17:32 UTC by NikitaBatalskiy

2020-09-09 19:15 UTC, dertosp requested changes
Ты закоммитил много файлов, которые никак не относятся к данной таске. Нужно их убрать + поправить то, что я обозначил

2020-09-09 19:15 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/BoxingTest.java
> +public class BoxingTest {
Этот файл здесь не нужен.

2020-09-09 19:15 UTC, dertosp commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +public class PrimitivesTest {
Этот файл здесь не нужен.

2020-09-09 19:15 UTC, dertosp commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +public class FooTest {
Этот файл здесь не нужен.

2020-09-09 19:15 UTC, dertosp commented on module1/src/test/java/net/broscorp/equals/hashcode/PersonTest.java
> +  private List<Person> persons = new ArrayList<>();
Сделай данные, которые используешь для тестирования, локальными для каждого теста.

2020-09-09 19:15 UTC, dertosp commented on module1/src/test/java/net/broscorp/equals/hashcode/PersonTest.java
> +  public void person1ShouldEqualsPerson2Person2ShouldEqualsPerson3AndPerson1ShouldEqualsPerson3() {
Посмотри в open-source проектах как люди называют тесты. Все тесты, в названиях которых есть слово person, нужно переименовать.

2020-09-09 19:35 UTC, Provsky commented on module1/src/test/java/net/broscorp/equals/hashcode/PersonTest.java
> +  public void cycleForList() {
Четкий тест, он остальное надо пофиксить.

2020-09-11 10:19 UTC, NikitaBatalskiy commented on module1/src/test/java/net/broscorp/equals/hashcode/PersonTest.java
> +  private List<Person> persons = new ArrayList<>();
Учту это в дальнейшем

2020-09-16 13:00 UTC, dertosp requested changes
Нужно вернуть указанный файл. Всё остальное 👍

2020-09-18 17:57 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +//package net.broscorp.generics;
У меня 10, не подойдет?

2020-09-18 17:58 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +//package net.broscorp.generics;
![image](https://user-images.githubusercontent.com/45694965/93629860-42b3d780-f9e9-11ea-8af9-f0f976dcc735.png)

2020-09-18 18:16 UTC, dertosp commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +//package net.broscorp.generics;
На сколько я знаю, для этого пакета нужна 8 (её скачать не составляет труда с сайта oracle или openjdk)

2021-03-24 15:02 UTC, closed without merging