patform
Broscorp-net/traineeship pull request #429
Opened 2020-08-30 18:03 UTC by NikitaBatalskiy

2020-09-09 19:25 UTC, dertosp requested changes
Ты закоммитил много файлов, которые никак не относятся к данной таске - нужно их убрать.

2020-09-09 19:25 UTC, dertosp commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +//package net.broscorp.generics;
Этот файл вообще менять не нужно в данной таске. Если у тебя проблемы с sun.reflect.generics.reflectiveObjects - тебе нужно поменять версию SDK для модуля (для IntelliJ IDEA: File -> Project Structure -> Modules -> Dependencies -> Module SDK -> 1.8)

2020-09-09 19:25 UTC, dertosp commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> +  public static void main(String[] args) {
Этот файл нужно просто удалить (и закоммитить).

2020-09-09 19:25 UTC, dertosp commented on module1/src/main/java/net/broscorp/equals/hashcode/Person.java
> +public class Person {
Этот файл никак не относится к данной таске.

2020-09-09 19:25 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/BoxingTest.java
> +public class BoxingTest {
Этот файл никак не относится к данной таске.

2020-09-09 19:25 UTC, dertosp commented on module1/src/test/java/net/broscorp/equals/hashcode/PersonTest.java
> +public class PersonTest {
Этот файл никак не относится к данной таске.

2020-09-09 19:25 UTC, dertosp commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +public class PrimitivesTest {
Этот файл никак не относится к данной таске.

2020-09-09 19:25 UTC, dertosp commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +public class FooTest {
Этот файл никак не относится к данной таске.

2020-09-09 19:41 UTC, Provsky commented on module1/src/main/java/net/broscorp/patform/java.gv
> +digraph java{
Хорошо, только нужно лишние файлы по убирать

2020-09-16 12:57 UTC, dertosp requested changes
Нужно вернуть указанный файл. Всё остальное 👍

2020-09-16 12:57 UTC, dertosp commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> -package net.broscorp.generics;
Этот файл не нужно удалять (я писал как можно исправить проблему с sun.reflect.generics.reflectiveObjects)

2020-10-12 08:00 UTC, Pakirava-Datsuma commented
![image](https://user-images.githubusercontent.com/1230991/95720584-1ef75080-0c7a-11eb-9ae6-275527496606.png)

2020-10-12 08:00 UTC, closed without merging