bytecode
Broscorp-net/traineeship pull request #430
Opened 2020-08-30 18:22 UTC by NikitaBatalskiy

2020-09-05 16:32 UTC, MentTea commented
Проверь свой пулл, твой пулл подтянул и прошлые твои коммиты, хотя должен был подтянуть, только bytecode.

2020-09-17 12:04 UTC, Pakirava-Datsuma requested changes
Topic completed!
Just some more things to make you an elegant software developer :)
Please, try to pay attention to the next things in future teamwork.
1. Avoid unnecessary editions in files. Especially when no other changes were made. Often we did not do them considerably. For example, they could appear after commits with some changes reverting.
2. Check extra newline at the end of each file. Github shows it in red. Usually IDE regarding that. But sometimes it is our duty.

These things do not relate to the topic. But they will make your pull requests more elegant and your reviewers happier :)
Personally I review my own pull requests twice at the end:
1. In the IDE before creating PR.
2. Directly on Github after PR is created.

2020-09-17 12:10 UTC, Pakirava-Datsuma commented
@NikitaBatalskiy если на английском непонятно — скажи, на каком удобнее

2020-09-17 17:12 UTC, NikitaBatalskiy commented
> @NikitaBatalskiy если на английском непонятно — скажи, на каком удобнее

@Pakirava-Datsuma, на русском пойму больше всего, естественно) хотя надо понимать на англ) не понял момент про джаваДоки, а так - мне надо внести изменения: добавить строку в скрипте, а файл MyCoolList уже не трогать, все правильно?

2020-09-18 07:11 UTC, Pakirava-Datsuma commented
> … момент про джаваДоки
Поищи, зачем нужны джавадоки, и проверь свой джавадок на соответствие этим рекомендациям.


> … файл MyCoolList уже не трогать
Сейчас в пулл реквесте видны изменения в этом файле.
![image](https://user-images.githubusercontent.com/1230991/93566959-82050880-f996-11ea-8245-6bb3224bf176.png)
Когда ты будешь работать в команде, такие изменения заставят твоего коллегу задуматься: _"Что такое важное делает эта пустая строка, что Никита решил её поменять?"_ То есть он начнет анализировать пустую строку. Я, конечно, сильно утрирую, но только чтобы проиллюстрировать идею: в пулл-реквесте меняются только те файлы, которые необходимо поменять. Поскольку для выполнения задания bytecode не нужно менять файл MyCoolList.java, то его и не должно быть видно в пулл-реквесте.

2020-09-19 10:26 UTC, NikitaBatalskiy commented
> > … момент про джаваДоки
> 
> Поищи, зачем нужны джавадоки, и проверь свой джавадок на соответствие этим рекомендациям.
> 
> > … файл MyCoolList уже не трогать
> 
> Сейчас в пулл реквесте видны изменения в этом файле.
> ![image](https://user-images.githubusercontent.com/1230991/93566959-82050880-f996-11ea-8245-6bb3224bf176.png)
> Когда ты будешь работать в команде, такие изменения заставят твоего коллегу задуматься: _"Что такое важное делает эта пустая строка, что Никита решил её поменять?"_ То есть он начнет анализировать пустую строку. Я, конечно, сильно утрирую, но только чтобы проиллюстрировать идею: в пулл-реквесте меняются только те файлы, которые необходимо поменять. Поскольку для выполнения задания bytecode не нужно менять файл MyCoolList.java, то его и не должно быть видно в пулл-реквесте.

Ну джавадоки нужны для описания метода, чтоб коллеги и я в будущем, когда вернусь к проекту, понимали, что делает тот или иной метод. Так же наш чекстайл требует джавадок конкретно там. Я правильно все понимаю?
Я не могу удалить файл MyCoolList.java, dertosp  в другом пулле говорил, что его нужно вернуть, когда я его удалял.

2020-09-29 06:29 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/bytecode/SomeClass.java
> +  /** This javadoc is required by checkstyle */
![image](https://user-images.githubusercontent.com/1230991/94520943-daa99080-0235-11eb-8002-4d9675ccdbc7.png)

2020-09-29 06:29 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -public class StyledClass {
why this class is deleted?

2020-09-29 06:33 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +}
Просто в пулл-реквесте не должно быть видно изменений в файле, где не меняется ничего из заявленного в топике.

2020-09-29 06:34 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> -}
Просто в пулл-реквесте не должно быть видно изменений в файле, где не меняется ничего из заявленного в топике

2020-09-29 07:38 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -public class StyledClass {
![image](https://user-images.githubusercontent.com/45694965/94527577-7982bc80-0237-11eb-985f-6d05b26a2793.png)

2020-09-29 07:38 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> -}
не знаю, как это сделать, к сожалению

2020-09-29 08:16 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -public class StyledClass {
Спасибо) Кстати, есть способ, удалить, но не добавлять в ПР

2020-09-29 08:28 UTC, NikitaBatalskiy commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -public class StyledClass {
Просто не ставить галочку напротив файла?)

2020-09-29 08:34 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> -public class StyledClass {
да. А чтобы файл не просился в каждый коммит — перенести в другой список
![image](https://user-images.githubusercontent.com/1230991/94533327-accd4780-0247-11eb-86d3-5eef21591657.png)

2020-10-12 07:52 UTC, Pakirava-Datsuma requested changes

2020-10-12 07:52 UTC, Pakirava-Datsuma commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +}
давай эту последнюю строчечку откатим, чтобы пулл реквест стал идеальным)

2021-03-24 15:02 UTC, closed without merging