Valueref
Broscorp-net/traineeship pull request #453
Opened 2020-09-03 11:00 UTC by aleksandr-zatsarnui

2020-09-09 18:37 UTC, dertosp requested changes
Один тест - это как-то маловато (можно ещё парочку как минимум придумать :) ). Плюс к каждому нужно не забыть добавить комментарий.

2020-09-09 18:37 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  public void testFooWithListExceptedTrue() {
Я бы исправил опечатку в названии

2020-09-09 18:37 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  @Test
В условии просили написать комментарии к тестам (кратко объяснить, почему происходит так).

2020-09-14 06:24 UTC, aleksandr-zatsarnui commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  @Test
Исправил.

2020-09-14 06:24 UTC, aleksandr-zatsarnui commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  public void testFooWithListExceptedTrue() {
упс) ну да)

2020-09-14 15:43 UTC, dertosp requested changes
Исправь то, что я написал. Ещё хочется, чтобы у тестов название передавало ожидаемые результаты обработки элементов, а не ожидаемые результаты assert'ов (чтобы было понятно, что происходит в тесте).

2020-09-14 15:43 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  public void testFooWithListExcectedTrue() {
Ты одну ошибку изменил на другую (подсказка: Expected)

2020-09-14 15:43 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  public void testFooWithDigitAndListExcectedTrue() {
Ты одну ошибку изменил на другую (подсказка: Expected)

2020-09-14 15:43 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +    Assertions.assertTrue(listSizeAfterCallMethod == 1);
Смысл этих двух сравнений? Одного будет достаточно.

2020-09-14 15:43 UTC, dertosp commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +    Assertions.assertTrue(listSizeAfterCallMethod == 1);
Смысл этих двух сравнений? Одного будет достаточно.

2020-09-14 15:54 UTC, aleksandr-zatsarnui commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +  public void testFooWithListExcectedTrue() {
точно) чете я прозевал опять.

2020-09-14 15:55 UTC, aleksandr-zatsarnui commented on module1/src/test/java/net/broscorp/boxing/valuerf/FooTest.java
> +    Assertions.assertTrue(listSizeAfterCallMethod == 1);
убрал.

2020-09-14 15:59 UTC, dertosp commented
👍

2021-03-24 15:02 UTC, closed without merging