Boxing
Broscorp-net/traineeship pull request #584
Opened 2021-03-19 14:03 UTC by SabHomyak

2021-03-24 15:15 UTC, pesua requested changes

2021-03-24 15:15 UTC, pesua commented on module1/src/test/java/net/broscorp/MyTest.java
> +  void compareNumbersShouldBeTrue() {
Эти три теста - агонь. Не понятно что сдесь делают предыдущие.

2021-03-27 13:35 UTC, SabHomyak commented
Удалил лишние тесты

2021-03-29 07:58 UTC, pesua commented
![image](https://user-images.githubusercontent.com/989360/112804909-a0eb0280-907d-11eb-9933-77e3c5137fac.png)

2021-03-29 07:58 UTC, closed without merging