Strings
Broscorp-net/traineeship pull request #590
Opened 2021-03-20 12:33 UTC by GrPerets

2021-03-24 15:45 UTC, pesua commented
Не нашел задания IV

2021-03-24 15:46 UTC, pesua commented
Не та кнопка)

2021-03-24 15:46 UTC, pesua requested changes

2021-03-24 15:46 UTC, pesua commented on module1/src/main/java/net/broscorp/strings/Main.java
> +public class Main {
Для проверки достаточно тестов. Такого рода класс будет без толку валяться в проекте и об него будут спотыкаться при рефакторинге.

2021-03-24 15:46 UTC, pesua commented on module1/src/main/java/net/broscorp/strings/Philologist.java
> +  public String randomSong(int bags, int verses) {
Проверь перевод первого параметра =)

2021-03-24 15:46 UTC, pesua commented on module1/src/main/java/net/broscorp/strings/Philologist.java
> +    for (int i = 0; i < verses; i++) {
Количество багов в новом куплете должно меняться. Глянь задание еще разок.

2021-03-30 07:38 UTC, pesua requested changes
Может я упоролся, но все еще не вижу задание IV.
Напиши имя метода его выполняющего, пожалуйста.

2021-03-30 10:05 UTC, GrPerets commented
Не доглядел, что некий функционал у меня выполнялся в ненужном методе main(). Все исправил)

2021-03-31 08:38 UTC, pesua reviewed
Есть метод, что разбивает на слова и есть метод, что печатает длинну слов. Но в требованиях было написано что нужен метод разбивающий и печатающий. Как-бы хочется закрыть уже, но и как-бы задание не совсем сделано.

2021-03-31 08:39 UTC, pesua commented
![image](https://user-images.githubusercontent.com/989360/113116015-b430d600-9215-11eb-9019-6e36a7afe590.png)

2021-03-31 08:39 UTC, closed without merging