Primitives
Broscorp-net/traineeship pull request #595
Opened 2021-03-20 16:28 UTC by IhorSamoshost

2021-03-24 15:56 UTC, pesua requested changes
Очень сложно. Для этого задания достаточно написать три-четыре теста, в каждом по паре операций и ассерту. Не нашел теста на погрешность операций с плавающей точкой.

2021-03-24 15:56 UTC, pesua commented on module1/src/main/java/net/broscorp/primitives/OperationsOnPrimitives.java
> +public class OperationsOnPrimitives {
Не понял предназначение этого класса. Он добавляет сложности, которая не требуется для выполнения задания.

2021-03-24 17:22 UTC, IhorSamoshost commented on module1/src/main/java/net/broscorp/primitives/OperationsOnPrimitives.java
> +public class OperationsOnPrimitives {
1. В задании требовалось "Написать класс с тестами на Junit". Как известно, тестами нужно что-то тестировать. Для большей универсальности я просто взял два функциональных интерфейса и сделал на их базе два кастомных метода, которые и тестировались в тестовом классе для соблюдения формальностей. Эти методы как раз и содержатся в классе OperationsOnPrimitives.
2. Тест на погрешность операций с плавающей точкой - последний в тестовом классе. Там делаются четыре ассерта:
- переменная float f1 = 4.6f при конвертации в double не равна 4.6;
- разность двух переменных типа double (4.6 - 2.3) при конвертации в float равна 2.3f;
- разность двух переменных типа float (4.6f - 2.3f) при конвертации в double не равна 2.3;
- при сравнении двух последних конвертированных разностей через assertEquals они считаются равными - показатель того, что при сравнении значение числа типа double обрезается до значения типа float и в такой разрядности они равны.
Мне кажется, я ничего лишнего не сделал и отразил все ньюансы)

2021-03-30 07:43 UTC, pesua commented on module1/src/main/java/net/broscorp/primitives/OperationsOnPrimitives.java
> +public class OperationsOnPrimitives {
Нам не нужна универсальность. Этот код должен решать только поставленную задачу и быть легко понимаем. Добавленная универсальность не факт что пригодится, зато точно затруднит поддержку этого кода.

2021-04-03 20:25 UTC, IhorSamoshost commented on module1/src/main/java/net/broscorp/primitives/OperationsOnPrimitives.java
> +public class OperationsOnPrimitives {
Вроде, всё отразил и достаточно упростил)

2021-04-04 13:58 UTC, pesua commented
Значительно лучше
![image](https://user-images.githubusercontent.com/989360/113511129-f2582d80-9566-11eb-93d8-05efa177ac4f.png)

2021-04-04 13:58 UTC, closed without merging