Gamelife
Broscorp-net/traineeship pull request #605
Opened 2021-03-22 22:25 UTC by GrPerets

2021-03-25 08:51 UTC, pesua requested changes
Хорошая реализация, есть парочка моментов на улучшить.

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +   * @param fileNameInput file with
With what? 😅

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    List<String> gameStartedList = readFromFile(fileNameInput);
Не понятное название переменной. Это список начатых игор?

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +          if ((numberOfLivingNeighbors(previousLifeCycle, i, j) == 2) || (
Читаемость кода не ухудшится если посчитать соседей один раз, а производительность улучшится.

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +  public int getNeighborPosition(int maxValue, int currentPosition, int step) {
Задача со звездочкой: написать этот метод без логических ветвлений

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +          stringBuilderForWriteToFile.append("\u0020");
Это какой-то спеициальный пробел? Не ясно почему бы не написать " ".

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +      ex.printStackTrace();
https://stackoverflow.com/a/7470693/5024717

2021-03-25 08:51 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    //
Закоментированный код в девелоп мерджить нельзя. Иначе в проекте быстро наступит бардак.

2021-03-30 07:56 UTC, pesua requested changes

2021-03-30 07:56 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +  public boolean[][] loopedAreaOfLife(boolean[][] currentAreaOfLife) {
Очень сложно, было лучше. Эта версия не годится. Она работает с произвольным размером? Почему тройки отнимаются?

При этом метод, который надо было переписать, вообще исчез. Так что и задача с озвездочкой не выполнена.

2021-03-30 10:17 UTC, GrPerets commented
В новой реализации, для того чтобы при поике соседей не выходить за пределы массива, я базовый массив расширял по +1 полю в каждую сторону соответствующими значениями. И да Она работает с произвольным размером. Почему -3: рассширенный массив больше на 2 (строки/столбца) и от length -1.
 Но я Вас, понял откачусь назад и выполню ваше предыдущее *задание

2021-03-31 08:41 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    int neighborPosition = (step + currentPosition + maxValue) % maxValue;
Ништяк

2021-03-31 08:42 UTC, pesua commented
![image](https://user-images.githubusercontent.com/989360/113116470-26091f80-9216-11eb-880e-662ecdaa8983.png)

2021-03-31 08:42 UTC, closed without merging