generics
Broscorp-net/traineeship pull request #612
Opened 2021-03-24 00:42 UTC by Libenko96

Solution for task - "generics"

2021-03-24 16:09 UTC, marvintik commented
Идея в том, чтобы сделать свою реализацию листа, а не использовать методы ArrayList

2021-03-31 08:49 UTC, pesua requested changes
Хорошая реализация, еще чуть улучшить бы тест.

2021-03-31 08:49 UTC, pesua commented on module1/src/test/java/net/broscorp/generics/MyCoolListTest.java
> +    assertDoesNotThrow(executable);
Это плохая проверка, много чего может пойти не так и при этом не бросить исключения.

2021-04-01 06:17 UTC, pesua commented on module1/src/test/java/net/broscorp/generics/MyCoolListTest.java
> +    assertTrue(list.map(function).get(0) instanceof Double);
Достаточно было бы вызвать мап единожды а потом проверять =)

2021-04-01 06:17 UTC, closed without merging