gc
Broscorp-net/traineeship pull request #632
Opened 2021-03-27 16:15 UTC by GrPerets

2021-03-31 17:00 UTC, pesua commented
Вроде-бы все верно, но автоматические проверки не пройдены, по правилам я даже не должен начинать такой пул смотреть.

2021-04-01 06:14 UTC, pesua requested changes
Нужно чинить код чтобы билд проходил, а не менять настройки проекта.

2021-04-01 09:34 UTC, GrPerets commented
Что бы выполнить задание, нужно переопределить метод finalize(), но тогда ругается checkstyle и соответственно not built. Предыдущее решение не прокатило. Можно ли тогда после выполнения №2 пункта задания удалить переоперделенный метод?

2021-04-01 22:00 UTC, GrPerets commented
https://broscorp-community.slack.com/archives/CQ1TZDT29/p1598510207000100?thread_ts=1598286962.005600&cid=CQ1TZDT29
Здесь Вы советуете, если это единственная ошибка оставить все как есть. Что мне делать, вернуть pom.xml как был?

2021-04-05 07:44 UTC, pesua commented on module1/src/main/java/net/broscorp/gc/results.md
> +Циклические зависимости не считаются ссылочными.
Как это работает? Сборщик ищет циклы каким-то образом?

2021-04-08 05:33 UTC, pesua commented
Теперь хорошо. Только забудь про Reference counting, он не используется уже лет двадцать, если я не путаю.

2021-04-08 05:33 UTC, closed without merging