equals.hashcode
Broscorp-net/traineeship pull request #649
Opened 2021-04-01 22:16 UTC by NesterovAlex

2021-04-02 06:28 UTC, Provsky requested changes

2021-04-02 06:28 UTC, Provsky commented on module1/src/test/java/net/broscorp/equals/hashcode/ComparableTest.java
> +    assertFalse(first.equals(third));
Все четко только один нюанс:
Сравнение первого со вторым тру, первого с третьим фолс.
А второго с третьим ты не сравнил.

2021-04-02 21:57 UTC, AlexandrLisitsa commented on module1/src/main/java/net/broscorp/equals/hashcode/Comparable.java
> +    result = prime * result + character;
а как ты смотришь на то, чтоб вычисление хеша привязать еще и к текущему времени :)?

2021-04-04 14:52 UTC, AlexandrLisitsa commented on module1/src/test/java/net/broscorp/equals/hashcode/ComparableTest.java
> +    int secondHashcode = second.hashCode();
Смотри какая ситуация. Выше я спрашивал на счет привязки даты к генерации хешкода.
Это не правильная стратегия. Одно из правил хешкода гласит что у тебя должна быть полная повторяемость результата не зависимо от дней недели, погоды на Марсе, твоего настроения и т.д. :)

Давай теперь разберемся почему этот тест отработал корректно.
Для генерации хеш кода ты использовал такие параметры как час, минута, секунда. При этом рантайм теста занимает куда меньшее время, по этому потенциальной проблемы не видно.
Для эксперимента добавь между вызовами first.hash и second.hash задержку в одну секунду и посмотри пройдет ли тест :)

2021-04-04 18:42 UTC, AlexandrLisitsa commented on module1/src/main/java/net/broscorp/checkstyle/StyledClass.java
> +    System.out.println("Hello checkstyle");
На сколько я помню, это самое первое задание, но оно попало в этот пул реквест.
Убери, пожалуйста, эти изменения. Пул реквест должен содержать только те изменения, которые были запрошены в реализации фичи.
Проверяющим на много легче будет вникнуть в контекст.

2021-07-22 06:53 UTC, closed without merging