Primitives
Broscorp-net/traineeship pull request #672
Opened 2021-04-10 18:37 UTC by RomanSmyrnov

2021-04-12 18:55 UTC, d-eisenberg commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    byte a = 127;
Тут ты забыл что-то, что покажет непосредственно, что случилось при переполнении.

2021-04-12 18:57 UTC, d-eisenberg commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    long a = 50500040L;
скажи, а разве число 50500040 не влазит в инт? Оно точно влазит, а значит твой тест не имеет смысла. Попробуй действительно большой лонг преобразовать в инт.

2021-04-12 18:58 UTC, d-eisenberg requested changes
Не спеши и попробуй выполнить заданее тщательнее.

2021-04-19 05:26 UTC, Provsky commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    Assertions.assertTrue(b < 0);
Напиши коментом тут, почему b<0 = Thrue.

2021-04-19 06:03 UTC, RomanSmyrnov commented on module1/src/test/java/net/broscorp/primitives/PrimitivesTest.java
> +    Assertions.assertTrue(b < 0);
При сужающем преобразовании отбрасываются биты, и в двоичном представлении число становится отрицательным

2021-05-17 17:18 UTC, closed without merging