valueref
Broscorp-net/traineeship pull request #713
Opened 2021-07-22 17:36 UTC by Andrii-Kniaziev

valueref task

2021-07-29 07:29 UTC, pesua requested changes
Закомиченна куча ненужных файлов. Если так делать на реальном проекте то он быстро скатится в беспорядок.

2021-07-29 07:29 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/README.md
> +### Алгоритм выполнения
Как это относится к заданию?)

2021-07-29 07:29 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  public void setUp() {
Зачем инициализация в отдельном методе?

2021-07-29 10:35 UTC, Andrii-Kniaziev commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  public void setUp() {
Тест пишется по принципу:
1. Подготовка тестовых данных.
2. Исполнение метода, который мы тестируем.
3. Проверка результата.

В тутореале видел что так делают, и подумал что ето относится к пункту 1 вашей инструкции. Уберу.

2021-07-29 10:36 UTC, Andrii-Kniaziev commented on module1/src/main/java/net/broscorp/gamelife/README.md
> +### Алгоритм выполнения
> Закомиченна куча ненужных файлов. Если так делать на реальном проекте то он быстро скатится в беспорядок.

Понял свою ошибку. Уберу.

2021-08-04 19:48 UTC, AlexandrLisitsa commented
👍

2021-08-04 19:48 UTC, closed without merging