valueref
Broscorp-net/traineeship pull request #719
Opened 2021-07-23 20:49 UTC by Alex99999999

2021-07-29 07:25 UTC, pesua requested changes

2021-07-29 07:25 UTC, pesua commented on module1/pom.xml
> +      <artifactId>junit-jupiter</artifactId>
А чем не подошел уже подключенный junit?

2021-07-29 07:25 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  @BeforeEach
Какое преимущество от вынесения инициализации теста в отдельный метод?

2021-07-29 07:25 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertEquals(12354652, num);
Чтобы понять этот тест надо понимать какие данные он получает на входе, а для этого надо бегать глазами по всему классу. Не удобно.

2021-08-01 14:04 UTC, Alex99999999 commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  @BeforeEach
В данном случае, никакого. Исправил

2021-08-09 09:46 UTC, Alex99999999 commented on module1/pom.xml
> +      <artifactId>junit-jupiter</artifactId>
В прошлом задании писал параметризированные тесты, чтобы их нормально заранить, пришлось подключить эту депенденси. В этот раз параметризированных тестов не писал, и обратно подключать тот junit, что был, уже не стал)

2021-08-09 09:52 UTC, Alex99999999 commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    assertEquals(12354652, num);
Исправил

2021-08-11 19:48 UTC, AlexandrLisitsa commented on module1/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
все еще висит помник отредаченый, должен быть только класс с тестом в пуле :)

2021-08-12 20:22 UTC, Alex99999999 commented on module1/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
А я все не мог понять, что не так)
Сделал

2021-08-16 17:33 UTC, closed without merging