Task 4: valueref
Broscorp-net/traineeship pull request #727
Opened 2021-07-25 01:15 UTC by Vitamin-68

Add test foo()
Test passed.
Build success.

2021-07-29 07:34 UTC, pesua requested changes

2021-07-29 07:34 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  void init() {
Зачем инициализация в отдельном методе?

2021-07-29 07:34 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    int firstParamBeforeFoo = firstParamFoo;
Тест будет проще читать если использовать конкретные значения.

2021-07-29 22:37 UTC, Vitamin-68 commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +  void init() {
Ну да, не прав, тестовый метод один и добавлять еще один только для инициализации смысла нет, исправляю.

2021-07-29 22:47 UTC, Vitamin-68 commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    int firstParamBeforeFoo = firstParamFoo;
Согласен, что будет проще, но в данном случае задача состояла не в том, чтобы в переменную firstParamBeforeFoo присвоить какое-то интовое значение, а в том, чтобы показать, что в эту переменную я сохраняю то же самое значение, которое я передаю затем в метод foo() и, после того как метод отработает,  я сравню его предыдущее состояние (firstParamBeforeFoo)  с тем что будет после метода и покажу, что оно не изменилось.

2021-07-31 18:27 UTC, Vitamin-68 commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    int firstParamBeforeFoo = firstParamFoo;
я пока оставляю код без изменений, но если Вы настаиваете, то конечно заменю на 
```
    int firstParamBeforeFoo = 1;
```

2021-08-04 20:13 UTC, AlexandrLisitsa commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    int firstParamFoo = 1;
привет :) очень запутанный тест. Попробуй упростить. Некоторые переменные лишние.

2021-08-04 22:30 UTC, Vitamin-68 commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +    int firstParamFoo = 1;
По прошествии нескольких дней еще раз посмотрел тест и сам запутался))) Упростил, думаю так значительно лучше.

2021-08-05 16:54 UTC, closed without merging