equals.hashcode
Broscorp-net/traineeship pull request #729
Opened 2021-07-26 06:03 UTC by Alex99999999

2021-07-29 08:26 UTC, pesua requested changes
Старайсе делать более простой и лаконичный код. Много лишних сложностей.

2021-07-29 08:26 UTC, pesua commented on module1/pom.xml
> +      <version>5.5.2</version>
Стандартного junit досточно

2021-07-29 08:26 UTC, pesua commented on module1/src/main/java/net/broscorp/equals/hashcode/EqualsHashcode.java
> +    return teamSize % 48;
Лучше когда оба поля используются в хешкоде.

2021-07-29 08:26 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      assertNotEquals(list.get(i), null);
Зачем это делать сто раз?

2021-07-29 08:26 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      list.add(new EqualsHashcode("Buzz", i));
Этот список очень усложнает код не ясно зачем. 
Нет никакой сложности чтоб создавать объекты на месте использования, а постоянные list.get натупляют и заставляют вспоминать что же там лежит в этой переменной.

2021-07-29 08:26 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      for (int j = i; j < list.size(); j++) {
Раз было решено использовать мапу то можно было обойтись без второго цикла.

2021-08-01 13:17 UTC, Alex99999999 commented on module1/src/main/java/net/broscorp/equals/hashcode/EqualsHashcode.java
> +    return teamSize % 48;
Да, в получении хешкода должны участвовать оба поля. Для целей задания была выбрана такая имплементация

2021-08-01 13:18 UTC, Alex99999999 commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      assertNotEquals(list.get(i), null);
Проверил все элементы из списка

2021-08-01 13:41 UTC, Alex99999999 commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      list.add(new EqualsHashcode("Buzz", i));
Этот список был создан, чтобы уменьшить количество бойлерплейт кода

2021-08-01 13:51 UTC, Alex99999999 commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      list.add(new EqualsHashcode("Buzz", i));
Создал объекты на месте их использования

2021-08-09 10:07 UTC, Alex99999999 commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +      for (int j = i; j < list.size(); j++) {
Исправил

2021-08-09 10:17 UTC, Alex99999999 commented on module1/pom.xml
> +      <version>5.5.2</version>
Этот вариант переехал с прошлого задания, на случай написания параметризированных тестов. В последующих заданиях уже не менял

2021-08-11 19:52 UTC, AlexandrLisitsa commented on module1/pom.xml
> +      <version>5.5.2</version>
старайся в пулах не делать изменения, которые не требуются. Таким образом ты явно покажешь что хочешь изменить в репозитории и другим будет проще разобраться. Мы просим не комитить ненужные файлы не просто так.

2021-08-13 06:02 UTC, Alex99999999 commented on module1/pom.xml
> +      <version>5.5.2</version>
Ок, понял.
Исправил

2021-09-08 14:07 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/hashcode/EqualsHashcodeTest.java
> +  void findObjectsWithEqualHashCodes() {
Было бы здорово сделать это покороче. Полтора экрана кода и четыре метода - сложновато для этой задачи.

2022-01-15 20:01 UTC, closed without merging