valueref
Broscorp-net/traineeship pull request #735
Opened 2021-07-27 10:05 UTC by MarkAb167

2021-07-29 07:47 UTC, pesua requested changes

2021-07-29 07:47 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +        assertEquals("d", list.get(list.indexOf("d")));
Все верно, но попробуй придумать способ проверки попроще.

2021-07-29 07:47 UTC, pesua commented on module1/src/test/java/net/broscorp/valueref/FooTest.java
> +        assertSame(1, i);
Почитай для чего нужен assertSame и напиши почему он не подходит для этого случая 🙃

2021-08-04 20:02 UTC, AlexandrLisitsa commented
👍

2021-08-04 20:02 UTC, closed without merging