patform
Broscorp-net/traineeship pull request #741
Opened 2021-07-27 16:06 UTC by MarkAb167

2021-07-30 08:07 UTC, pesua requested changes
А что с ответсвенностями?

2021-08-04 20:07 UTC, AlexandrLisitsa commented on module1/src/main/java/net/broscorp/patform/diagram.gv
> +    "JVM" -> "JRE" [ label = "implements"]
разве JRE является частью JVM :)?

2021-08-05 10:00 UTC, MarkAb167 commented on module1/src/main/java/net/broscorp/patform/diagram.gv
> +    "JVM" -> "JRE" [ label = "implements"]
перепутал ) пофиксил

2021-08-11 19:54 UTC, AlexandrLisitsa commented
👍

2021-08-11 19:54 UTC, closed without merging