generics
Broscorp-net/traineeship pull request #760
Opened 2021-07-31 10:34 UTC by MarkAb167

2021-08-02 07:48 UTC, pesua requested changes
Не вижу реализации второго пункта из задания

2021-08-02 07:48 UTC, pesua commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +  public MyCoolList<T> map(Function<T, T> f) {
От такой функции мало пользы, хочется уметь мапить из одного типа в другой.

2021-08-03 10:50 UTC, MarkAb167 commented on module1/src/main/java/net/broscorp/generics/MyCoolList.java
> +  public MyCoolList<T> map(Function<T, T> f) {
- Ок, сделал

2021-08-11 20:08 UTC, AlexandrLisitsa commented
👍

2021-08-11 20:08 UTC, closed without merging