inner.classes
Broscorp-net/traineeship pull request #763
Opened 2021-07-31 12:22 UTC by MarkAb167

2021-08-02 07:52 UTC, pesua requested changes

2021-08-02 07:52 UTC, pesua commented on module1/src/main/java/net/broscorp/inner/classes/MyCoolList.java
> +  public Iterator iterator() {
Почему итератор не типизированный?

2021-08-02 07:52 UTC, pesua commented on module1/src/test/java/net/broscorp/inner/classes/MyCoolListTest.java
> +class MyCoolListTest {
Не хватает тестов поведения итератора. Не проверено еще минимум два момента.

2021-08-03 14:31 UTC, MarkAb167 commented on module1/src/main/java/net/broscorp/inner/classes/MyCoolList.java
> +  public Iterator iterator() {
пофиксил

2021-08-03 14:31 UTC, MarkAb167 commented on module1/src/test/java/net/broscorp/inner/classes/MyCoolListTest.java
> +class MyCoolListTest {
Добавил

2021-08-11 20:15 UTC, AlexandrLisitsa commented on module1/src/main/java/net/broscorp/inner/classes/MyCoolList.java
> +      return myList.get(currCursor);
return myList.get(cursor++);
можно было еще так сделать чтоб не создавать еще одну переменную :)

2021-08-11 20:15 UTC, AlexandrLisitsa commented on module1/src/test/java/net/broscorp/inner/classes/MyCoolListTest.java
> +    MyCoolList<Integer> list = new MyCoolList<>();
первый тест от этого ничем не отличается, вроде бы :)

2021-08-11 20:15 UTC, AlexandrLisitsa commented
👍

2021-08-11 20:15 UTC, closed without merging