override.overload
Broscorp-net/traineeship pull request #769
Opened 2021-07-31 15:37 UTC by MarkAb167

2021-08-02 07:59 UTC, pesua requested changes
Все ок кроме последнего пункта

2021-08-02 07:59 UTC, pesua commented on module1/src/main/java/net/broscorp/override/overload/MathOperation.java
> + * Overriding - using a method from a class or interface of an ancestor,
Если это ответ на шестой пункт то он не полный, нужно было написать именно назначение анотации.

2021-08-03 14:52 UTC, MarkAb167 commented on module1/src/main/java/net/broscorp/override/overload/MathOperation.java
> + * Overriding - using a method from a class or interface of an ancestor,
Ок, развернул ответ

2021-08-11 20:26 UTC, AlexandrLisitsa commented
👍

2021-08-11 20:26 UTC, closed without merging