equals.hashcode
Broscorp-net/traineeship pull request #837
Opened 2021-08-19 12:56 UTC by IhorYutinDev

2021-09-10 14:17 UTC, pesua requested changes

2021-09-10 14:17 UTC, pesua commented on module1/src/test/java/net/broscorp/equals/MyEqualsHashcodeTest.java
> +
Необходимо было проверить все инварианты Equals там пять правил.

2021-09-14 07:10 UTC, IhorYutinDev commented on module1/src/test/java/net/broscorp/equals/MyEqualsHashcodeTest.java
> +
It is reflexive: for any non-null reference value x, x.equals(x) should return true.
It is symmetric: for any non-null reference values x and y, x.equals(y) should return true if and only if y.equals(x) returns true.
It is transitive: for any non-null reference values x, y, and z, if x.equals(y) returns true and y.equals(z) returns true, then x.equals(z) should return true.
It is consistent: for any non-null reference values x and y, multiple invocations of x.equals(y) consistently return true or consistently return false, provided no information used in equals comparisons on the objects is modified.
For any non-null reference value x, x.equals(null) should return false.

2021-09-14 07:10 UTC, IhorYutinDev commented on module1/src/test/java/net/broscorp/equals/MyEqualsHashcodeTest.java
> +
Добавил 5 тестов на проверку вышеуказанных правил

2021-11-25 11:54 UTC, Provsky commented
гуд

2021-11-25 11:55 UTC, closed without merging