gamelife
Broscorp-net/traineeship pull request #839
Opened 2021-08-20 02:45 UTC by Vitamin-68

all test passed
Build success

2021-09-10 14:24 UTC, pesua requested changes
sumAroundCells трудновато читать, а так - неплохо

2021-09-10 14:24 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +class GameOfLife {
Зачем убрал модификаторы доступа?

2021-09-10 14:24 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    int[][] arrField = new int[fieldRows][fieldColumns];
Зачем int?

2021-09-10 14:24 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +  private int prevIndex(int index, int value) {
Сможешь сделать вместо этих двух методов один и без логического ветвления внутри?)

2021-09-11 21:34 UTC, Vitamin-68 commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +class GameOfLife {
Потому что Идея подсвечивала этот модификатор и предлагала изменить его на package-private, что не влияло в данном случае на работу проекта. Но раз это принципиально - вернул модификатор "public" на место.

2021-09-11 23:21 UTC, Vitamin-68 commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    int[][] arrField = new int[fieldRows][fieldColumns];
Да, для  условий этой задачи хватает и типа "byte", это уменьшит размер массивов в 4 раза в отличие от "int", но для заданных условий задачи с максимальным размером поля 25х25 эта разница мне показалась несущественной - 625 байт против 2500, и таких массивов всего 2. К тому же тип "int" для JAVA является типом по умолчанию для операций с целыми числами, поэтому не нужно будет следить за приведением типов при операциях со значениями полей, как например в этом случае для типа "byte":
arrField[i][j] = row[j].equals("O") ? (byte) 0 : 1;   
Поэтому и использовал для массива тип "int", но опять таки, если это принципиально - изменил на "byte".
PS. если уж озадачиться экономией памяти, то можно использовать тип "BitSet" для хранения данных побайтово, но возможно придется поменять логику и как это скажется на скорости работы программы я не знаю. Да и задачи такой не стояло... :)

2021-09-11 23:34 UTC, Vitamin-68 commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +  private int prevIndex(int index, int value) {
> sumAroundCells трудновато читать
заменил название на более логичное - sumNeighborCells 

> Сможешь сделать вместо этих двух методов один и без логического ветвления внутри?)
как-то и самому это не нравилось, когда написал. Да, сделал, так значительно эстетичней выглядит))

2021-09-13 12:13 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +    int[][] arrField = new int[fieldRows][fieldColumns];
Вообще, если не думать про производительность а только про корректность то там должны быть булеаны. У клеток есть только два состояния. В первую очередь всегда стоит думать как не наделать багов. =)
Если еще и про производительность то надо пробовать битсет и мерять скорость до/после.

2021-09-13 12:14 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +class GameOfLife {
Когда надо посмотреть побольше пулов за ограниченное время хочется чтоб там были только изменения по сути). Хотел узнать, может на изменение были серьезные причины.

2021-09-13 12:16 UTC, pesua commented on module1/src/main/java/net/broscorp/gamelife/GameOfLife.java
> +  private int calculateIndex(int fieldSize, int indexValue) {
![image](https://user-images.githubusercontent.com/989360/133081761-91ae76e4-9cc4-4489-b325-ab5ac55b462b.png)

2021-09-13 12:16 UTC, pesua commented
![image](https://user-images.githubusercontent.com/989360/133081864-77640a96-5e8d-49b3-aaad-7f8df5c7c955.png)

2021-09-13 12:16 UTC, closed without merging