exception
Broscorp-net/traineeship pull request #847
Opened 2021-09-07 08:20 UTC by IhorYutinDev

2021-09-13 12:52 UTC, pesua requested changes

2021-09-13 12:52 UTC, pesua commented on module1/src/main/java/net/broscorp/exceptions/README.md
> +    - __try-with-resources__ который открывает файл, но получает __IOException__, F его и печатает прощание в __finally__.
Што?)

2021-09-13 12:52 UTC, pesua commented on module1/src/main/java/net/broscorp/exceptions/exception.gv
> +    "IOException" -> "SQL" [label = "Checked"]
Не знаю такого исключения)

2021-09-13 12:52 UTC, pesua commented on module1/src/test/java/net/broscorp/gamelife/exception/MyExceptionTest.java
> +    //open file
Этот коментарий не несет никакой дополнительной инфорации, не стоит такие оставлять

2021-09-13 12:52 UTC, pesua commented on module1/src/test/java/net/broscorp/gamelife/exception/MyExceptionTest.java
> +      //e.printStackTrace();
Закоментированный код в пулл попадать не должен

2021-09-14 08:01 UTC, IhorYutinDev commented on module1/src/main/java/net/broscorp/exceptions/README.md
> +    - __try-with-resources__ который открывает файл, но получает __IOException__, F его и печатает прощание в __finally__.
превозмогает - исправил

2021-09-14 08:02 UTC, IhorYutinDev commented on module1/src/main/java/net/broscorp/exceptions/exception.gv
> +    "IOException" -> "SQL" [label = "Checked"]
SQLException исправил

2021-09-14 08:02 UTC, IhorYutinDev commented on module1/src/test/java/net/broscorp/gamelife/exception/MyExceptionTest.java
> +    //open file
лишний коммент убрал

2021-09-14 08:03 UTC, IhorYutinDev commented on module1/src/test/java/net/broscorp/gamelife/exception/MyExceptionTest.java
> +      //e.printStackTrace();
исправил коммент

2021-11-25 12:01 UTC, Provsky requested changes

2021-11-25 12:01 UTC, Provsky commented on module1/src/test/java/net/broscorp/gamelife/exception/MyExceptionTest.java
> +  void myIoExceptionTest() {
В тесте добавь проверку, а то он не свалится не как.)

2022-01-15 20:02 UTC, closed without merging