Gc
Broscorp-net/traineeship pull request #909
Opened 2021-11-24 11:28 UTC by MrMarkutan

2021-11-25 21:07 UTC, Provsky requested changes
В принципе хорошо только надо почистить немного

2021-11-25 21:07 UTC, Provsky commented on module1/src/test/java/net/broscorp/gc/MyListTest.java
> +  @SneakyThrows
Это необходимая аннотация?

2021-11-25 21:07 UTC, Provsky commented on module1/src/main/java/net/broscorp/gc/MyList.java
> + * . Класс для проверки задания
От этого комментария нет пользы

2021-11-25 21:07 UTC, Provsky commented on module1/src/main/java/net/broscorp/gc/MyList.java
> +    //    System.out.println("Added object " + num + " to MyList");
Как и от этого

2021-11-26 06:48 UTC, MrMarkutan commented on module1/src/test/java/net/broscorp/gc/MyListTest.java
> +  @SneakyThrows
да, так как Thread.sleep() может выбросить InterruptedException

2021-11-26 06:49 UTC, MrMarkutan commented on module1/src/test/java/net/broscorp/gc/MyListTest.java
> +  @SneakyThrows
а в 3 тесте нету необходимости в такой аннотации

2021-11-26 06:50 UTC, MrMarkutan commented on module1/src/main/java/net/broscorp/gc/MyList.java
> + * . Класс для проверки задания
Знаю, но build падал с предупреждением о необходимости добавить тут коммент

2021-11-26 06:50 UTC, MrMarkutan commented on module1/src/main/java/net/broscorp/gc/MyList.java
> +    //    System.out.println("Added object " + num + " to MyList");
Согласен, здесь удалить

2021-11-29 21:59 UTC, Provsky commented
Окей

2021-11-29 21:59 UTC, closed without merging